### ISSUE TITLE
Unable to process URL (Tags error)

### ISSUE THREAD

**Issue by jebesen** [unaguil/sphinx-swagger#24]
I get this error:

Unable to process URL: http://localhost:5000/swagger.json                       
Traceback (most recent call last):
  File "/home/jebesen/dev/crypto/Trade4Lambos/microservices/mongo_data/env/lib/python3.6/site-packages/sphinxcontrib/swaggerdoc/swaggerv2_doc.py", line 228, in run
    groups = self.group_tags(api_desc)
  File "/home/jebesen/dev/crypto/Trade4Lambos/microservices/mongo_data/env/lib/python3.6/site-packages/sphinxcontrib/swaggerdoc/swaggerv2_doc.py", line 199, in group_tags
    for tag in method['tags']:
TypeError: list indices must be integers or slices, not str

**Comment by JimBacon** [comment]
Yes, me too.
My swagger.json contains the following snippet for a path.
The parameters section is being interpreted as a method, which it isn't, and then the code breaks when it cannot find a tags list within it.
Did you come up with a solution @jebesen?
```
        "/permissions/{ID}": {
            "parameters": [
                {
                    "name": "ID",
                    "in": "path",
                    "required": true,
                    "type": "integer"
                }
            ],
            "get": {
                "responses": {
                    "403": {
                        "description": "User lacks permissions to access this route",
                        "schema": {
                            "$ref": "#/definitions/PermissionDenied"
                        }
                    },
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Permission"
                        }
                    }
                },
                "operationId": "get_permission_resource",
                "tags": [
                    "permissions"
                ]
            },

```

**Comment by JimBacon** [comment]
A workaround is to use https://github.com/sphinx-contrib/openapi instead.
