### ISSUE TITLE
swaggerv2doc error: `for tag in api_desc['tags']: KeyError: 'tags'`

### ISSUE THREAD

**Issue by moigagoo** [unaguil/sphinx-swagger#5]
`tags` is an optional field, and it happens to be missing in my Swagger file. So the extension fails with a KeyError:

```
Unable to process URL: http://localhost:8000/swagger.json
Traceback (most recent call last):
  File "c:\users\moigagoo\projects\job\ref_sdp_api\.venv\lib\site-packages\sphinx_swagger\swaggerv2_doc.py", line 151, in run
    groups = self.group_tags(api_desc)
  File "c:\users\moigagoo\projects\job\ref_sdp_api\.venv\lib\site-packages\sphinx_swagger\swaggerv2_doc.py", line 125, in group_tags
    for tag in api_desc['tags']:
KeyError: 'tags'
```

I tried working around this by adding:

```
if 'tags' not in api_desc.keys(): return groups
```

and the error does not pop out this way, but there's no output as well. I haven't tried other approaches yet.

**Comment by moigagoo** [comment]
UPD: Adding `tags` to the top level works around the issue, but there are other points where similar mistake leads to an error:

```
Unable to process URL: http://localhost:8000/swagger.json
Traceback (most recent call last):
  File "c:\users\moigagoo\projects\job\ref_sdp_api\.venv\lib\site-packages\sphinx_swagger\swaggerv2_doc.py", line 159, in run
    section += self.make_method(path, method_type, method)
  File "c:\users\moigagoo\projects\job\ref_sdp_api\.venv\lib\site-packages\sphinx_swagger\swaggerv2_doc.py", line 118, in make_method
    swagger_node += self.make_parameters(method['parameters'])
KeyError: 'parameters'
```

**Comment by miraculixx** [comment]
I was able to get it to work by providing a swagger V2 spec as follows:

_top level_ - a list of [tag objects](http://swagger.io/specification/#tagObject)

```
...
"tags" : [
      {
         "name" : "category"
      },
      ...
], 
...
```

_operation level_ - a list of tag names (find _Operation Object_ / _Fixed Fields_ in the [swagger specs](http://swagger.io/specification/)) 

```
...
"/category/{id}/" : {
         "get" : {
            ...
            "tags" : [
               "category"
            ],
            ...
         },
...
```
